# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ping_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(962, 954)
        MainWindow.setWindowIcon(QtGui.QIcon('ping.ico'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plaintxt1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plaintxt1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.plaintxt1.setAutoFillBackground(False)
        self.plaintxt1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plaintxt1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plaintxt1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plaintxt1.setDocumentTitle("")
        self.plaintxt1.setReadOnly(True)
        self.plaintxt1.setPlainText("")
        self.plaintxt1.setBackgroundVisible(False)
        self.plaintxt1.setObjectName("plaintxt1")
        self.horizontalLayout_2.addWidget(self.plaintxt1)
        self.plaintxt2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plaintxt2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plaintxt2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plaintxt2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plaintxt2.setReadOnly(True)
        self.plaintxt2.setObjectName("plaintxt2")
        self.horizontalLayout_2.addWidget(self.plaintxt2)
        self.plaintxt3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plaintxt3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plaintxt3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plaintxt3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plaintxt3.setReadOnly(True)
        self.plaintxt3.setObjectName("plaintxt3")
        self.horizontalLayout_2.addWidget(self.plaintxt3)
        self.plaintxt4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plaintxt4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plaintxt4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plaintxt4.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plaintxt4.setReadOnly(True)
        self.plaintxt4.setObjectName("plaintxt4")
        self.horizontalLayout_2.addWidget(self.plaintxt4)
        self.plaintxt5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plaintxt5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plaintxt5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plaintxt5.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plaintxt5.setReadOnly(True)
        self.plaintxt5.setObjectName("plaintxt5")
        self.horizontalLayout_2.addWidget(self.plaintxt5)
        self.plaintxt6 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plaintxt6.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plaintxt6.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plaintxt6.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.plaintxt6.setReadOnly(True)
        self.plaintxt6.setObjectName("plaintxt6")
        self.horizontalLayout_2.addWidget(self.plaintxt6)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 962, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Andres Ping Dashboard"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
